### ISSUE TITLE
Installed attobot3, made releases, but nothing seems to be happening

### ISSUE THREAD

**Issue by cnaak** [attobot3/attobot3#1]
I have `attobot3` installed on my [LBTheory](https://github.com/LBTheory) organization for all repositories thereof.

Since installation of the bot, I have made two releases in my [HermiteTensorPoly.jl](https://github.com/LBTheory/HermiteTensorPoly.jl) repository (git tag + GitHub release). This should trigger `autobot3` to do its thing; however, nothing seems to be happening: no PR's to `METADATA.jl`, no emails...

Please help/advise. Thanks in advance!

**Comment by KristofferC** [comment]
Sorry, this repo is non functional and should likely be deleted.

**Comment by cnaak** [comment]
Thanks. Please consider updating your `README.md` with this information.

**Comment by KristofferC** [comment]
Done
